# Describes the format for available services for bibliotheek_be

get_lowest_fuel_price:
  description: >
    Get the lowest fuel price in the neighbourhood of a specific location.
  fields:
    fuel_type:
      description: >
        The type of fuel to look for, supported options: super95, super98 or diesel
      example: diesel
    country:
      description: >
        The country to look for, supported options: BE / FR / LU
      example: BE
    postalcode:
      description: >
        The postalcode to look for
      example: 3620
    town:
      description: >
        (Optonal) The town to look for
      example: Lanaken
    max_distance:
      description: >
        Max distance in km around postal code to look for lowest fuel price, eg search 5km around postal code
      example: 5
    filter:
      description: >
        (Optional) Filter out only specific supplier brands, leave empty if any supplier brand is allowed
      example: Shell
    
get_lowest_fuel_price_on_route:
  description: >
    Get the lowest fuel price on a route between 2 locations.
  fields:
    fuel_type:
      description: >
        The type of fuel to look for, supported options: super95, super98 or diesel
      example: diesel
    country:
      description: >
        The country to look for, supported options: BE / FR / LU
      example: BE
    from_postalcode:
      description: >
        The postalcode to look for as start of the route
      example: 3620
    to_postalcode:
      description: >
        The postalcode to look for as end of the route
      example: 3620
    filter:
      description: >
        (Optional) Filter out only specific supplier brands, leave empty if any supplier brand is allowed
      example: Shell
    ors_api_key:
      description: >
        OpenRouteService API key for route requests (free key available at https://openrouteservice.org/)
      example: abcdefghijklmnopqrstuvwxyz123456_-
    here_api_key:
      description: >
        Here API key for route requests (free key available at https://platform.here.com/)
      example: abcdefghijklmnopqrstuvwxyz123456_-